# Generated by Django 4.1.1 on 2022-09-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cloud",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=108)),
                ("Address", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="restaurants",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=108)),
                ("Address", models.TextField()),
                ("distance", models.IntegerField(blank=True, null=True)),
                ("rating", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
